.TH PFTW 3 2015-08-03 "" ""
.SH NAME
pftw \- parallel file tree walk
.SH SYNOPSIS
.nf
.B #include <pftw.h>

.BI "int pftw_init(int " num_threads ");"

.BI "int pftw(const char *" dirpath ,
.BI "        int (*" fn ") (const char *" fpath ", const struct stat *" sb ,
.BI "                   int " typeflag ", struct FTW *" ftwbuf ", void *" arg ),
.BI "        int " nopenfd ", int " flags ", void *" arg );

.BI "int pftw_deinit();"

.SH DESCRIPTION

.BR pftw ()
does the same as 
.BR nftw (3),
but in parallel threads [based on
.BR pthreads (7)].
The additional argument
.I arg
is just an arbitrary user-defined argument. Before running
.BR pftw ()
it's required to run
.BR pftw_init ()
where
.I num_threads
is a number of workers threads for
.BR pftw ().
Argument
.I nopenfd
is ignored. Some
.BR nftw (3)
.I flags
may be not supported.

.SH RETURN VALUE
Functions
.BR pftw_init "(), " pftw ()
and
.BR pftw_deinit ()
returns 0 on success and
.I errno
if an error occurs.

.SH AUTHOR
Dmitry Yu Okunev <dyokunev@ut.mephi.ru> 0x8E30679C

.SH SUPPORT
You can get support on IRC-channel in Freenode "#clsync" or on
github's issue tracking system of the libpftw repository
.IR https://github.com/xaionaro/libpftw .

.SH SEE ALSO
.BR nftw (3)
